// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: hQRGGCqC6n6YZiRJ8GQC4P
// Component: el51C_ukCXEN
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: hQRGGCqC6n6YZiRJ8GQC4P/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: el51C_ukCXEN/css

import MarkerAltIcon from "./icons/PlasmicIcon__MarkerAlt"; // plasmic-import: SdIHIdwjY_4/icon
import MarkerIcon from "./icons/PlasmicIcon__Marker"; // plasmic-import: BIt_PMbaYoS/icon
import DownwardTriangleIcon from "./icons/PlasmicIcon__DownwardTriangle"; // plasmic-import: 0J9a-KrBWLr/icon
import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: LCvb9lxvcz2/icon
import Facebook1Icon from "./icons/PlasmicIcon__Facebook1"; // plasmic-import: vf8jTTpAlWS/icon

export type PlasmicHomepage__VariantMembers = {};

export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  home?: p.Flex<"div">;
  dashboardDesktop?: p.Flex<"div">;
  background?: p.Flex<"div">;
  car307549712801?: p.Flex<"div">;
  nightSkyBackground?: p.Flex<"div">;
  sidebar?: p.Flex<"div">;
  thumbs?: p.Flex<"div">;
  _7043543811Aa48709F0665Bfc991Aa4A1?: p.Flex<"div">;
  _7043543811Aa48709F0665Bfc991Aa4A2?: p.Flex<"div">;
  _7043543811Aa48709F0665Bfc991Aa4A3?: p.Flex<"div">;
  _7043543811Aa48709F0665Bfc991Aa4A4?: p.Flex<"div">;
  menu?: p.Flex<"div">;
  button?: p.Flex<"div">;
  buttonOutline?: p.Flex<"div">;
  loremIpsumDolorSitAmetConsecteturAdipiscingElitNuncAccumsanSedDiamUtConsecteturNuncMaximusMagnaDolorEgetAccumsanLeoTemporEget?: p.Flex<"div">;
  photoOfTheDayNasa?: p.Flex<"div">;
  social?: p.Flex<"div">;
  rectangle47?: p.Flex<"div">;
};

export interface DefaultHomepageProps {
  className?: string;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  dataFetches?: PlasmicHomepage__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <React.Fragment>
      {}
      {}

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"home"}
            data-plasmic-override={overrides.home}
            className={classNames(defaultcss.all, sty.home)}
          >
            <div
              data-plasmic-name={"dashboardDesktop"}
              data-plasmic-override={overrides.dashboardDesktop}
              className={classNames(defaultcss.all, sty.dashboardDesktop)}
            >
              <div
                data-plasmic-name={"background"}
                data-plasmic-override={overrides.background}
                className={classNames(defaultcss.all, sty.background)}
              >
                <div
                  data-plasmic-name={"car307549712801"}
                  data-plasmic-override={overrides.car307549712801}
                  className={classNames(defaultcss.all, sty.car307549712801)}
                >
                  <div
                    data-plasmic-name={"nightSkyBackground"}
                    data-plasmic-override={overrides.nightSkyBackground}
                    className={classNames(
                      defaultcss.all,
                      sty.nightSkyBackground
                    )}
                  />
                </div>
              </div>

              <div
                data-plasmic-name={"sidebar"}
                data-plasmic-override={overrides.sidebar}
                className={classNames(defaultcss.all, sty.sidebar)}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__sf1Mp
                )}
              >
                {"©2021 GeorgeC."}
              </div>

              <div
                data-plasmic-name={"thumbs"}
                data-plasmic-override={overrides.thumbs}
                className={classNames(defaultcss.all, sty.thumbs)}
              >
                <div
                  data-plasmic-name={"_7043543811Aa48709F0665Bfc991Aa4A1"}
                  data-plasmic-override={
                    overrides._7043543811Aa48709F0665Bfc991Aa4A1
                  }
                  className={classNames(
                    defaultcss.all,
                    sty._7043543811Aa48709F0665Bfc991Aa4A1
                  )}
                />

                <div
                  data-plasmic-name={"_7043543811Aa48709F0665Bfc991Aa4A2"}
                  data-plasmic-override={
                    overrides._7043543811Aa48709F0665Bfc991Aa4A2
                  }
                  className={classNames(
                    defaultcss.all,
                    sty._7043543811Aa48709F0665Bfc991Aa4A2
                  )}
                />

                <div
                  data-plasmic-name={"_7043543811Aa48709F0665Bfc991Aa4A3"}
                  data-plasmic-override={
                    overrides._7043543811Aa48709F0665Bfc991Aa4A3
                  }
                  className={classNames(
                    defaultcss.all,
                    sty._7043543811Aa48709F0665Bfc991Aa4A3
                  )}
                />

                <div
                  data-plasmic-name={"_7043543811Aa48709F0665Bfc991Aa4A4"}
                  data-plasmic-override={
                    overrides._7043543811Aa48709F0665Bfc991Aa4A4
                  }
                  className={classNames(
                    defaultcss.all,
                    sty._7043543811Aa48709F0665Bfc991Aa4A4
                  )}
                />
              </div>

              <div
                data-plasmic-name={"menu"}
                data-plasmic-override={overrides.menu}
                className={classNames(defaultcss.all, sty.menu)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__fxkl6
                  )}
                >
                  {"HOME"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__u5S88
                  )}
                >
                  {"TOPICS"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__shfRu
                  )}
                >
                  {"NASA TV"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__tnD9P
                  )}
                >
                  {"MISSIONS"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__s7Zbs
                  )}
                >
                  {"DOWNLOADS"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__lw1Sh
                  )}
                >
                  {"ABOUT"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__uu0U
                  )}
                >
                  {"CONTACT"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox___7T7H3
                  )}
                >
                  {"SUPPORT"}
                </div>

                {false ? (
                  <MarkerAltIcon
                    className={classNames(defaultcss.all, sty.svg__sStxT)}
                    role={"img"}
                  />
                ) : null}

                <MarkerIcon
                  className={classNames(defaultcss.all, sty.svg__srdGk)}
                  role={"img"}
                />
              </div>

              <DownwardTriangleIcon
                className={classNames(defaultcss.all, sty.svg__ttG8F)}
                role={"img"}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__ngyl0
                )}
              >
                {"NEWS"}
              </div>

              <div
                data-plasmic-name={"button"}
                data-plasmic-override={overrides.button}
                className={classNames(defaultcss.all, sty.button)}
              >
                <div
                  data-plasmic-name={"buttonOutline"}
                  data-plasmic-override={overrides.buttonOutline}
                  className={classNames(defaultcss.all, sty.buttonOutline)}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__s0Urc
                  )}
                >
                  {"LEARN MORE"}
                </div>
              </div>

              <div
                data-plasmic-name={
                  "loremIpsumDolorSitAmetConsecteturAdipiscingElitNuncAccumsanSedDiamUtConsecteturNuncMaximusMagnaDolorEgetAccumsanLeoTemporEget"
                }
                data-plasmic-override={
                  overrides.loremIpsumDolorSitAmetConsecteturAdipiscingElitNuncAccumsanSedDiamUtConsecteturNuncMaximusMagnaDolorEgetAccumsanLeoTemporEget
                }
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.loremIpsumDolorSitAmetConsecteturAdipiscingElitNuncAccumsanSedDiamUtConsecteturNuncMaximusMagnaDolorEgetAccumsanLeoTemporEget
                )}
              >
                {
                  "\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc accumsan sed diam ut consectetur. Nunc maximus magna dolor, eget accumsan leo tempor eget.\n"
                }
              </div>

              <div
                data-plasmic-name={"photoOfTheDayNasa"}
                data-plasmic-override={overrides.photoOfTheDayNasa}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.photoOfTheDayNasa
                )}
              >
                {"Photo of the Day\nNASA\n\n\n\n"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__d0EdD
                )}
              >
                {
                  "Each day a different image or photograph of our universe is featured, along with a brief explanation written by a professional astronomer."
                }
              </div>
            </div>

            <div
              data-plasmic-name={"social"}
              data-plasmic-override={overrides.social}
              className={classNames(defaultcss.all, sty.social)}
            >
              <div
                data-plasmic-name={"rectangle47"}
                data-plasmic-override={overrides.rectangle47}
                className={classNames(defaultcss.all, sty.rectangle47)}
              />

              <VectorIcon
                className={classNames(defaultcss.all, sty.svg__x9RD)}
                role={"img"}
              />

              <Facebook1Icon
                className={classNames(defaultcss.all, sty.svg__c4Qk)}
                role={"img"}
              />
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__nKgfw
              )}
            >
              {"YOURLOGO"}
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "home",
    "dashboardDesktop",
    "background",
    "car307549712801",
    "nightSkyBackground",
    "sidebar",
    "thumbs",
    "_7043543811Aa48709F0665Bfc991Aa4A1",
    "_7043543811Aa48709F0665Bfc991Aa4A2",
    "_7043543811Aa48709F0665Bfc991Aa4A3",
    "_7043543811Aa48709F0665Bfc991Aa4A4",
    "menu",
    "button",
    "buttonOutline",
    "loremIpsumDolorSitAmetConsecteturAdipiscingElitNuncAccumsanSedDiamUtConsecteturNuncMaximusMagnaDolorEgetAccumsanLeoTemporEget",
    "photoOfTheDayNasa",
    "social",
    "rectangle47"
  ],
  home: [
    "home",
    "dashboardDesktop",
    "background",
    "car307549712801",
    "nightSkyBackground",
    "sidebar",
    "thumbs",
    "_7043543811Aa48709F0665Bfc991Aa4A1",
    "_7043543811Aa48709F0665Bfc991Aa4A2",
    "_7043543811Aa48709F0665Bfc991Aa4A3",
    "_7043543811Aa48709F0665Bfc991Aa4A4",
    "menu",
    "button",
    "buttonOutline",
    "loremIpsumDolorSitAmetConsecteturAdipiscingElitNuncAccumsanSedDiamUtConsecteturNuncMaximusMagnaDolorEgetAccumsanLeoTemporEget",
    "photoOfTheDayNasa",
    "social",
    "rectangle47"
  ],
  dashboardDesktop: [
    "dashboardDesktop",
    "background",
    "car307549712801",
    "nightSkyBackground",
    "sidebar",
    "thumbs",
    "_7043543811Aa48709F0665Bfc991Aa4A1",
    "_7043543811Aa48709F0665Bfc991Aa4A2",
    "_7043543811Aa48709F0665Bfc991Aa4A3",
    "_7043543811Aa48709F0665Bfc991Aa4A4",
    "menu",
    "button",
    "buttonOutline",
    "loremIpsumDolorSitAmetConsecteturAdipiscingElitNuncAccumsanSedDiamUtConsecteturNuncMaximusMagnaDolorEgetAccumsanLeoTemporEget",
    "photoOfTheDayNasa"
  ],
  background: ["background", "car307549712801", "nightSkyBackground"],
  car307549712801: ["car307549712801", "nightSkyBackground"],
  nightSkyBackground: ["nightSkyBackground"],
  sidebar: ["sidebar"],
  thumbs: [
    "thumbs",
    "_7043543811Aa48709F0665Bfc991Aa4A1",
    "_7043543811Aa48709F0665Bfc991Aa4A2",
    "_7043543811Aa48709F0665Bfc991Aa4A3",
    "_7043543811Aa48709F0665Bfc991Aa4A4"
  ],
  _7043543811Aa48709F0665Bfc991Aa4A1: ["_7043543811Aa48709F0665Bfc991Aa4A1"],
  _7043543811Aa48709F0665Bfc991Aa4A2: ["_7043543811Aa48709F0665Bfc991Aa4A2"],
  _7043543811Aa48709F0665Bfc991Aa4A3: ["_7043543811Aa48709F0665Bfc991Aa4A3"],
  _7043543811Aa48709F0665Bfc991Aa4A4: ["_7043543811Aa48709F0665Bfc991Aa4A4"],
  menu: ["menu"],
  button: ["button", "buttonOutline"],
  buttonOutline: ["buttonOutline"],
  loremIpsumDolorSitAmetConsecteturAdipiscingElitNuncAccumsanSedDiamUtConsecteturNuncMaximusMagnaDolorEgetAccumsanLeoTemporEget:
    [
      "loremIpsumDolorSitAmetConsecteturAdipiscingElitNuncAccumsanSedDiamUtConsecteturNuncMaximusMagnaDolorEgetAccumsanLeoTemporEget"
    ],
  photoOfTheDayNasa: ["photoOfTheDayNasa"],
  social: ["social", "rectangle47"],
  rectangle47: ["rectangle47"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  home: "div";
  dashboardDesktop: "div";
  background: "div";
  car307549712801: "div";
  nightSkyBackground: "div";
  sidebar: "div";
  thumbs: "div";
  _7043543811Aa48709F0665Bfc991Aa4A1: "div";
  _7043543811Aa48709F0665Bfc991Aa4A2: "div";
  _7043543811Aa48709F0665Bfc991Aa4A3: "div";
  _7043543811Aa48709F0665Bfc991Aa4A4: "div";
  menu: "div";
  button: "div";
  buttonOutline: "div";
  loremIpsumDolorSitAmetConsecteturAdipiscingElitNuncAccumsanSedDiamUtConsecteturNuncMaximusMagnaDolorEgetAccumsanLeoTemporEget: "div";
  photoOfTheDayNasa: "div";
  social: "div";
  rectangle47: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicHomepage__Fetches;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    home: makeNodeComponent("home"),
    dashboardDesktop: makeNodeComponent("dashboardDesktop"),
    background: makeNodeComponent("background"),
    car307549712801: makeNodeComponent("car307549712801"),
    nightSkyBackground: makeNodeComponent("nightSkyBackground"),
    sidebar: makeNodeComponent("sidebar"),
    thumbs: makeNodeComponent("thumbs"),
    _7043543811Aa48709F0665Bfc991Aa4A1: makeNodeComponent(
      "_7043543811Aa48709F0665Bfc991Aa4A1"
    ),
    _7043543811Aa48709F0665Bfc991Aa4A2: makeNodeComponent(
      "_7043543811Aa48709F0665Bfc991Aa4A2"
    ),
    _7043543811Aa48709F0665Bfc991Aa4A3: makeNodeComponent(
      "_7043543811Aa48709F0665Bfc991Aa4A3"
    ),
    _7043543811Aa48709F0665Bfc991Aa4A4: makeNodeComponent(
      "_7043543811Aa48709F0665Bfc991Aa4A4"
    ),
    menu: makeNodeComponent("menu"),
    button: makeNodeComponent("button"),
    buttonOutline: makeNodeComponent("buttonOutline"),
    loremIpsumDolorSitAmetConsecteturAdipiscingElitNuncAccumsanSedDiamUtConsecteturNuncMaximusMagnaDolorEgetAccumsanLeoTemporEget:
      makeNodeComponent(
        "loremIpsumDolorSitAmetConsecteturAdipiscingElitNuncAccumsanSedDiamUtConsecteturNuncMaximusMagnaDolorEgetAccumsanLeoTemporEget"
      ),
    photoOfTheDayNasa: makeNodeComponent("photoOfTheDayNasa"),
    social: makeNodeComponent("social"),
    rectangle47: makeNodeComponent("rectangle47"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
